projects:
  cmkapi:
    schemaPath: >-
      Users/alexander/Documents/_school/MobileApps&Svcs/Campus-Mood-Kit-Amplify/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
